spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    group:
      local:
        - common
      qa:
        - common
      prod:
        - common
  application:
    name: speech

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/speech
    username: root
    password: admin
